export const LIST_BLACKLIST = "LIST_BLACKLIST"

export const LoanRequestActionTypes = {
    SHOW_ALL_LOAN_REQUESTS: 'SHOW_ALL_LOAN_REQUESTS',
    VERIFY_CREDENTIAL_HASH: 'VERIFY_CREDENTIAL_HASH',
    QUERY_MULTI_PARTY_LOAN: 'QUERY_MULTI_PARTY_LOAN',
    QUERY_MAL_RECORDS: 'QUERY_MAL_RECORDS'
}
