export const LIST_BLACKLIST = "LIST_BLACKLIST"

export const LoanRequestActionTypes = {
    SHOW_ALL_LOAN_REQUESTS: 'SHOW_ALL_LOAN_REQUESTS',
    VERIFY_CREDENTIAL_HASH: 'VERIFY_CREDENTIAL_HASH',
    QUERY_MULTI_PARTY_LOAN: 'QUERY_MULTI_PARTY_LOAN',
    QUERY_MAL_RECORDS: 'QUERY_MAL_RECORDS',
}

// 公司
export const COMPANY_ACTION_TYPES = {
    SHOW_ALL_BLACKLIST: "SHOW_ALL_BLACKLIST",
    LOAN_REQUEST: "USER_LOAN_REQUEST",
    USER_LOAN_RECORDS: "USER_LOAN_RECORDS",
    MULTI_PARTY_INFO: "MULTI_PARTY_INFO",
}

// 用户
export const USER_ACTION_TYPES = {
    USER_LOAN_REQUEST: "USER_LOAN_REQUEST",
    USER_LOAN_RECORDS: "USER_LOAN_RECORDS",
    USER_CREDENTIALS: "USER_CREDENTIALS",
}

// 政府
export const GOVERNMENT_ACTION_TYPES = {
    VERIFIED_USERS: "VERIFIED_USERS",
    UNVERIFIED_USERS: "UNVERIFIED_USERS",
    WEIDS: "WEIDS",
    ALL_CREDENTIALS_INFO: "ALL_CREDENTIALS_INFO"
}

// 通用
export const COMMON_ACTION_TYPES = {
    
}






